Repository Guardians-DSC/dados, pull requests merged in 2023-10, with the labels that each got.

#39 adicionando colab: distribuição de inscritos
  SISU/notebooks/distribuição_de_inscritos_ _análise.ipynb
Labels: AnaliseSisu

#37 Adiciona o collab analisando os gastos onde os municípios são informados.
  orcamento/notebooks/municipiosInformados_dadosUFCG.ipynb
Labels: AnaliseGastos

#46 Inserindo o colab relacionado à Análise das notas dos aprovados em CC…
  SISU/notebooks/dados_areas_sisucc/notas_SISU_CC.ipynb
Labels: AnaliseSisu, Hacktoberfest, HacktoberfestAccepted

#45 Desempenho dos alunos nas cadeiras de cálculo
  desempenho_academico/notebooks/DesempenhoCadeirasCCC.ipynb
Labels: AnaliseDesempenho, Hacktoberfest, HacktoberfestAccepted

#47 Envio da analise de dados das aprovações da disciplina de TC
  desempenho_academico/notebooks/aprovações_tc.ipynb
Labels: AnaliseDesempenho, Hacktoberfest, HacktoberfestAccepted

#50 analise_de_gastos_por_regiao
  orcamento/notebooks/Analise_de_gastos_por_região.ipynb
Labels: AnaliseGastos, Hacktoberfest, HacktoberfestAccepted
